[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "build"

[functions]
  node_bundler = "esbuild"

[functions."*"]
  node_version = "18"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
