[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "build"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[functions."claude"]
  included_files = ["netlify/functions/claude.js"]

[functions."gpt"]
  included_files = ["netlify/functions/gpt.js"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
